//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_new.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class employee
    {
        public employee()
        {

        }

        public int e_id { get; set; }
        public string name { get; set; }

        [Required]
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> s_id { get; set; }
        public string designation { get; set; }
        public string empl_type { get; set; }
        public string status { get; set; }
        public Nullable<int> wage { get; set; }
        public Nullable<int> b_id { get; set; }

       

    }

    public partial class employeeModel
    {
        public employeeModel(){

        }
        public int e_id { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public string name { get; set; }

        [Required(ErrorMessage = "Required Field")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string email { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public string password { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Required Field")]
        [System.ComponentModel.DataAnnotations.Compare("password", ErrorMessage = "Password doesn't match.")]
        [DataType(DataType.Password)]
        public string cpassword { get; set; }
        public Nullable<int> s_id { get; set; }
        public string designation { get; set; }
        public string empl_type { get; set; }
        public string status { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public Nullable<int> wage { get; set; }
        public Nullable<int> b_id { get; set; }

        public SelectList emaildrop { get; set; }
    }








}
