//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class freelancer
    {
        public int f_id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public Nullable<int> wage { get; set; }
        public Nullable<int> s_id { get; set; }
        public Nullable<int> b_id { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual space space { get; set; }
    }
}
