//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_new.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class issue
    {
        public int i_id { get; set; }
        public int s_id { get; set; }
        public string priority { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public string issue1 { get; set; }
        public int e_id { get; set; }
    
        public virtual space space { get; set; }
    }
}
