//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int m_id { get; set; }
        public int e_id { get; set; }
        public string message1 { get; set; }
        public System.DateTime m_date { get; set; }
        public int s_id { get; set; }
    
        public virtual space space { get; set; }
    }
}
