//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_new.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class task
    {
        public int t_id { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public int e_id { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public string task_desc { get; set; }
        public string status { get; set; }
        public int s_id { get; set; }
    
        public virtual space space { get; set; }
    }
}
