//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_new.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class wage
    {
        public int e_id { get; set; }
        public int b_id { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }

        [NotMapped]
        public int cardno { get; set; }

        [NotMapped]
        public int cvv { get; set; }
    
        public virtual Business Business { get; set; }
    }

    public partial class wageModel
    {
        public int e_id { get; set; }
        public int b_id { get; set; }

        [Required(ErrorMessage = "Required Field")]
        public int amount { get; set; }
        public System.DateTime date { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Required Field")]
        [StringLength(12, MinimumLength = 12,ErrorMessage = "Enter 12 digit cardno.!")]
        public int cardno { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "Required Field")]
        [StringLength(3, MinimumLength = 3, ErrorMessage = "Enter proper CVV!")]
        public int cvv { get; set; }

        public virtual Business Business { get; set; }
    }
}
